name: Bug Report
description: This is a silly test
title: "[BUG] "
labels: bug
body:
- type: checkboxes
  id: cat-preferences
  attributes:
    label: What kinds of cats do you like?
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: Black cat
- type: dropdown
  id: download
  attributes:
    label: How did you find your cat?
    options:
      - Pound/Shelter
      - Friends
      - On the street
      - Cats are awful
  validations:
    required: true
